name: Spring Boot CI/CD to Azure
run-name: Start build at branch ${{ github.ref_name }} by @${{ github.actor }}

# Set up condition for CI pipeline
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
# Hanlde concurrency push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Setup JDK 17, build maven and docker file
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # Stable version
          cache: maven 
      - name: Run unit tests
        run: mvn test
        
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Build Docker image
        run: docker build -t tourism-image:latest .
